# Generated by Django 3.0 on 2021-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaintbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_email', models.EmailField(max_length=50)),
                ('p_complaint', models.CharField(max_length=1000)),
            ],
        ),
    ]
